### ISSUE TITLE
Implement function to throw error when channel name is not specified. 

### ISSUE THREAD

**Issue by secrashi** [secrashi/Connect-Intellect#2]
Currently, if we try to create a channel without giving any name to it, it will generate a string like `# !members-Z8TBhk-SmUjX4WQbQVfLWPXySbfsHsIEFLpiL2aRNMY` as Channel Name. Hence, implement the function to throw an error when name is not specified.

**Comment by gurpreet-legend** [comment]
Can I work on this issue ?

**Comment by secrashi** [comment]
Hi @gurpreet-legend, yes you can take up this issue. 
Regarding the sign-in problem, did you run both client and server before trying to sign in? Also, to get more clarity, open the developers' console to check the error message. If you still face the problem, let me know!

**Comment by gurpreet-legend** [comment]
> Hi @gurpreet-legend, yes you can take up this issue. Regarding the sign-in problem, did you run both client and server before trying to sign in? Also, to get more clarity, open the developers' console to check the error message. If you still face the problem, let me know!

Yes, mam, I have run both client and server separately.
I am getting this error on the server-side, when I try to Sign in :
`[SiteError: This method can only be used server-side using your API Secret, use client = stream.connect(key, secret);]`

**Comment by secrashi** [comment]
Okay, I understood the issue. I'll get it sorted.

**Comment by gurpreet-legend** [comment]
Mam, please do update the Contributing.md file, as I have created my stream account as per your instructions

**Comment by secrashi** [comment]
I have updated the readme for installation steps, which will clear your issue.

**Comment by gurpreet-legend** [comment]
@secrashi mam, I have set up the environment variables as per your instructions but I am still getting this error on the server-side :
![image](https://user-images.githubusercontent.com/75157493/135747868-6d90cc07-351c-4b82-891b-6c01e0d6c225.png)


And moreover, there was a redundant `ads` variable in the catch block in `server/controllers/auth.js` which was giving an error before, I removed that, it was not necessary right ?
![image](https://user-images.githubusercontent.com/75157493/135747980-41bf4c26-b0e7-49ca-a7dd-50e160968a0f.png)

**Comment by sakshi-dhamija** [comment]
> @secrashi mam, I have set up the environment variables as per your instructions but I am still getting these two errors on the server-side :

Hi Gurpreet, Go to stream chat, open your app> chat>overview and add this link  `https://connect-intellect.herokuapp.com`  to webhooks, if the problem still occurs let me know:

> And moreover, there was a redundant `ads` variable in the catch block in `server/controllers/auth.js` which was giving an error before, I removed that, it was not necessary right ?

Ya, that must have been added by mistake.
